{% set name = "pubchem-tools" %}
{% set version = "0.1.2a" %}



package:
  name: "{{ name|lower }}"
  version: "{{ version }}"



source:
  url: https://github.com/GES-compchem/{{ name }}/archive/refs/tags/{{ version }}.zip

build:
  noarch: python
  number: 0



requirements:
  host:
    - python>=3.9
    - pip
    - setuptools
    - numpy
    - requests

  run:
    - python>=3.9
    - requests


about:
  home: The package home page
  license: UNKNOWN
  license_family: OTHER
  license_file:
  summary: ""
  doc_url:
  dev_url:



extra:
  recipe-maintainers:
    - GES-compchem